// This file is generated by running
// yarn run generate-mapping
// Do not modify this file directly
import raw from 'raw.macro';

export default {
  '20-02-01': raw('../cdcupdates/screening/20-02-01.txt'),
  '20-02-11': raw('../cdcupdates/screening/20-02-11.txt'),
  '20-02-24': raw('../cdcupdates/screening/20-02-24.txt'),
  '20-02-29': raw('../cdcupdates/screening/20-02-29.txt'),
  '20-03-01': raw('../cdcupdates/screening/20-03-01.txt'),
  '20-03-02': raw('../cdcupdates/screening/20-03-02.txt'),
  '20-03-03': raw('../cdcupdates/screening/20-03-03.txt'),
  '20-03-04': raw('../cdcupdates/screening/20-03-04.txt'),
  '20-03-05': raw('../cdcupdates/screening/20-03-05.txt'),
  '20-03-06': raw('../cdcupdates/screening/20-03-06.txt'),
  '20-03-07': raw('../cdcupdates/screening/20-03-07.txt'),
};
