// This file is generated by running
// yarn run generate-mapping
// Do not modify this file directly
import raw from 'raw.macro';

export default {
  '20-02-12': raw('../cdcupdates/management/20-02-12.txt'),
  '20-02-26': raw('../cdcupdates/management/20-02-26.txt'),
  '20-02-29': raw('../cdcupdates/management/20-02-29.txt'),
  '20-03-01': raw('../cdcupdates/management/20-03-01.txt'),
  '20-03-02': raw('../cdcupdates/management/20-03-02.txt'),
  '20-03-03': raw('../cdcupdates/management/20-03-03.txt'),
  '20-03-04': raw('../cdcupdates/management/20-03-04.txt'),
};
