// This file is generated by running
// yarn run generate-mapping
// Do not modify this file directly
import raw from 'raw.macro';

export default {
  '20-02-01': raw('../cdcupdates/screening/20-02-01.txt'),
  '20-02-11': raw('../cdcupdates/screening/20-02-11.txt'),
  '20-02-24': raw('../cdcupdates/screening/20-02-24.txt'),
  '20-02-29': raw('../cdcupdates/screening/20-02-29.txt'),
  '20-03-01': raw('../cdcupdates/screening/20-03-01.txt'),
  '20-03-02': raw('../cdcupdates/screening/20-03-02.txt'),
};
