// This file is generated by running
// yarn run generate-mapping
// Do not modify this file directly
import raw from 'raw.macro';

export default {
  '20-02-11': raw('../cdcupdates/20-02-11.txt'),
  '20-03-01': raw('../cdcupdates/20-03-01.txt'),
};
